// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/kallydev/privacy/ent/predicate"
	"github.com/kallydev/privacy/ent/wbmodel"
)

// WBModelDelete is the builder for deleting a WBModel entity.
type WBModelDelete struct {
	config
	hooks    []Hook
	mutation *WBModelMutation
}

// Where adds a new predicate to the delete builder.
func (wmd *WBModelDelete) Where(ps ...predicate.WBModel) *WBModelDelete {
	wmd.mutation.predicates = append(wmd.mutation.predicates, ps...)
	return wmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wmd *WBModelDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wmd.hooks) == 0 {
		affected, err = wmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WBModelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wmd.mutation = mutation
			affected, err = wmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wmd.hooks) - 1; i >= 0; i-- {
			mut = wmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmd *WBModelDelete) ExecX(ctx context.Context) int {
	n, err := wmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wmd *WBModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: wbmodel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wbmodel.FieldID,
			},
		},
	}
	if ps := wmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, wmd.driver, _spec)
}

// WBModelDeleteOne is the builder for deleting a single WBModel entity.
type WBModelDeleteOne struct {
	wmd *WBModelDelete
}

// Exec executes the deletion query.
func (wmdo *WBModelDeleteOne) Exec(ctx context.Context) error {
	n, err := wmdo.wmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wbmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wmdo *WBModelDeleteOne) ExecX(ctx context.Context) {
	wmdo.wmd.ExecX(ctx)
}
