// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/kallydev/privacy/ent/wbmodel"
)

// WBModel is the model entity for the WBModel schema.
type WBModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WbNumber holds the value of the "uid" field.
	WbNumber int64 `json:"wb_uids,omitempty"`
	// PhoneNumber holds the value of the "phone_number" field.
	PhoneNumber int64 `json:"phone_number,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WBModel) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // uid
		&sql.NullInt64{}, // phone_number
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WBModel fields.
func (wm *WBModel) assignValues(values ...interface{}) error {
	if m, n := len(values), len(wbmodel.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	wm.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field uid", values[0])
	} else if value.Valid {
		wm.WbNumber = value.Int64
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field phone_number", values[1])
	} else if value.Valid {
		wm.PhoneNumber = value.Int64
	}
	return nil
}

// Update returns a builder for updating this WBModel.
// Note that, you need to call WBModel.Unwrap() before calling this method, if this WBModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (wm *WBModel) Update() *WBModelUpdateOne {
	return (&WBModelClient{config: wm.config}).UpdateOne(wm)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (wm *WBModel) Unwrap() *WBModel {
	tx, ok := wm.config.driver.(*txDriver)
	if !ok {
		panic("ent: WBModel is not a transactional entity")
	}
	wm.config.driver = tx.drv
	return wm
}

// String implements the fmt.Stringer.
func (wm *WBModel) String() string {
	var builder strings.Builder
	builder.WriteString("WBModel(")
	builder.WriteString(fmt.Sprintf("id=%v", wm.ID))
	builder.WriteString(", uid=")
	builder.WriteString(fmt.Sprintf("%v", wm.WbNumber))
	builder.WriteString(", phone_number=")
	builder.WriteString(fmt.Sprintf("%v", wm.PhoneNumber))
	builder.WriteByte(')')
	return builder.String()
}

// WBModels is a parsable slice of WBModel.
type WBModels []*WBModel

func (wm WBModels) config(cfg config) {
	for _i := range wm {
		wm[_i].config = cfg
	}
}
